language: java
sudo: false
install: true

jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: code-not-found-cxf-jaxws
    token:
      secure: $SONAR_TOKEN

env:
- PROJECT_DIR=cxf-jaxws-helloworld-example
- PROJECT_DIR=cxf-jaxws-logging-logback
- PROJECT_DIR=cxf-jaxws-soap-header-explicit
- PROJECT_DIR=cxf-jaxws-soap-header
- PROJECT_DIR=cxf-jaxws-ticketagent

script:
- cd $PROJECT_DIR
- mvn test -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

notifications:
  email: false
